// =====> COMMENTS constants
// FETCH actions
export const GET_COMMENTS_FAILURE = 'GET_COMMENTS_FAILURE';
export const GET_COMMENTS_REQUEST = 'GET_COMMENTS_REQUEST';
export const GET_COMMENTS_SUCCESS = 'GET_COMMENTS_SUCCESS';

// ADD actions
export const ADD_COMMENT_FAILURE = 'ADD_COMMENT_FAILURE';
export const ADD_COMMENT_REQUEST = 'ADD_COMMENT_REQUEST';
export const ADD_COMMENT_SUCCESS = 'ADD_COMMENT_SUCCESS';

// DELETE actions
export const DELETE_COMMENT_FAILURE = 'DELETE_COMMENT_FAILURE';
export const DELETE_COMMENT_REQUEST = 'DELETE_COMMENT_REQUEST';
export const DELETE_COMMENT_SUCCESS = 'DELETE_COMMENT_SUCCESS';

// EDIT actions
export const EDIT_COMMENT_FAILURE = 'EDIT_COMMENT_FAILURE';
export const EDIT_COMMENT_REQUEST = 'EDIT_COMMENT_REQUEST';
export const EDIT_COMMENT_SUCCESS = 'EDIT_COMMENT_SUCCESS';

// set the current comment and commentable type/id
export const TOGGLE_COMMENTS_FORM = 'TOGGLE_COMMENTS_FORM';
export const UPDATE_COMMENTS_DICTIONARY = 'UPDATE_COMMENTS_DICTIONARY';

// =====> FAVOURITES constants
// IS FAVOURITED actions
export const CHECK_IS_FAVOURITED_FAILURE = 'CHECK_IS_FAVOURITED_FAILURE';
export const CHECK_IS_FAVOURITED_REQUEST = 'CHECK_IS_FAVOURITED_REQUEST';
export const CHECK_IS_FAVOURITED_SUCCESS = 'CHECK_IS_FAVOURITED_SUCCESS';
export const UPDATE_IS_FAVOURITED_STATUS = 'UPDATE_IS_FAVOURITED_STATUS';

// // FETCH actions
export const GET_FAVOURITES_FAILURE = 'GET_FAVOURITES_FAILURE';
export const GET_FAVOURITES_REQUEST = 'GET_FAVOURITES_REQUEST';
export const GET_FAVOURITES_SUCCESS = 'GET_FAVOURITES_SUCCESS';
export const UPDATE_FAVOURITES_DICTIONARY = 'UPDATE_FAVOURITES_DICTIONARY';

// // ADD actions
export const ADD_FAVOURITE_FAILURE = 'ADD_FAVOURITE_FAILURE';
export const ADD_FAVOURITE_REQUEST = 'ADD_FAVOURITE_REQUEST';
export const ADD_FAVOURITE_SUCCESS = 'ADD_FAVOURITE_SUCCESS';

// // DELETE actions
export const DELETE_FAVOURITE_FAILURE = 'DELETE_FAVOURITE_FAILURE';
export const DELETE_FAVOURITE_REQUEST = 'DELETE_FAVOURITE_REQUEST';
export const DELETE_FAVOURITE_SUCCESS = 'DELETE_FAVOURITE_SUCCESS';

// // EDIT actions
// export const EDIT_FAVOURITE_FAILURE = 'EDIT_FAVOURITE_FAILURE';
// export const EDIT_FAVOURITE_REQUEST = 'EDIT_FAVOURITE_REQUEST';
// export const EDIT_FAVOURITE_SUCCESS = 'EDIT_FAVOURITE_SUCCESS';

// // set the current comment and commentable type/id
export const TOGGLED_FAVOURITED_STATUS = 'TOGGLED_FAVOURITED_STATUS';
// export const UPDATE_FAVOURITES_DICTIONARY = 'UPDATE_FAVOURITES_DICTIONARY';

//  =====> MOVIE constants
// FETCH actions
export const FETCH_MOVIE_FAILURE = 'FETCH_MOVIE_FAILURE';
export const FETCH_MOVIE_REQUEST = 'FETCH_MOVIE_REQUEST';
export const FETCH_MOVIE_SUCCESS = 'FETCH_MOVIE_SUCCESS';
// REGISTRATION actions
export const REGISTER_MOVIE_FAILURE = 'REGISTER_MOVIE_FAILURE';
export const REGISTER_MOVIE_NOT_NEEDED = 'REGISTER_MOVIE_NOT_NEEDED';
export const REGISTER_MOVIE_REQUEST = 'REGISTER_MOVIE_REQUEST';
export const REGISTER_MOVIE_SUCCESS = 'REGISTER_MOVIE_SUCCESS';
export const VALIDATE_MOVIE_REGISTRATION = 'VALIDATE_MOVIE_REGISTRATION';
// unused
// export const SET_CURRENT_MOVIE = 'SET_CURRENT_MOVIE';
