// set immutable constants for movie actions

// async actions
export const FETCH_COMMENTS_FAILURE = 'FETCH_COMMENTS_FAILURE';
export const FETCH_COMMENTS_REQUEST = 'FETCH_COMMENTS_REQUEST';
export const FETCH_COMMENTS_SUCCESS = 'FETCH_COMMENTS_SUCCFUL';

export const UPDATE_CURRENT_COMMENTS = 'UPDATE_CURRENT_COMMENTS';
